// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: server/proto/byter_service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ByterService_Upload_FullMethodName = "/GophKeeper.server.proto.ByterService/Upload"
	ByterService_Unload_FullMethodName = "/GophKeeper.server.proto.ByterService/Unload"
)

// ByterServiceClient is the client API for ByterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ByterServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBytesRequest, UploadBytesResponse], error)
	Unload(ctx context.Context, in *UnloadBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UnloadBytesResponse], error)
}

type byterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewByterServiceClient(cc grpc.ClientConnInterface) ByterServiceClient {
	return &byterServiceClient{cc}
}

func (c *byterServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBytesRequest, UploadBytesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ByterService_ServiceDesc.Streams[0], ByterService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadBytesRequest, UploadBytesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ByterService_UploadClient = grpc.ClientStreamingClient[UploadBytesRequest, UploadBytesResponse]

func (c *byterServiceClient) Unload(ctx context.Context, in *UnloadBytesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UnloadBytesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ByterService_ServiceDesc.Streams[1], ByterService_Unload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnloadBytesRequest, UnloadBytesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ByterService_UnloadClient = grpc.ServerStreamingClient[UnloadBytesResponse]

// ByterServiceServer is the server API for ByterService service.
// All implementations must embed UnimplementedByterServiceServer
// for forward compatibility.
type ByterServiceServer interface {
	Upload(grpc.ClientStreamingServer[UploadBytesRequest, UploadBytesResponse]) error
	Unload(*UnloadBytesRequest, grpc.ServerStreamingServer[UnloadBytesResponse]) error
	mustEmbedUnimplementedByterServiceServer()
}

// UnimplementedByterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedByterServiceServer struct{}

func (UnimplementedByterServiceServer) Upload(grpc.ClientStreamingServer[UploadBytesRequest, UploadBytesResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedByterServiceServer) Unload(*UnloadBytesRequest, grpc.ServerStreamingServer[UnloadBytesResponse]) error {
	return status.Error(codes.Unimplemented, "method Unload not implemented")
}
func (UnimplementedByterServiceServer) mustEmbedUnimplementedByterServiceServer() {}
func (UnimplementedByterServiceServer) testEmbeddedByValue()                      {}

// UnsafeByterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ByterServiceServer will
// result in compilation errors.
type UnsafeByterServiceServer interface {
	mustEmbedUnimplementedByterServiceServer()
}

func RegisterByterServiceServer(s grpc.ServiceRegistrar, srv ByterServiceServer) {
	// If the following call panics, it indicates UnimplementedByterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ByterService_ServiceDesc, srv)
}

func _ByterService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ByterServiceServer).Upload(&grpc.GenericServerStream[UploadBytesRequest, UploadBytesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ByterService_UploadServer = grpc.ClientStreamingServer[UploadBytesRequest, UploadBytesResponse]

func _ByterService_Unload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UnloadBytesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ByterServiceServer).Unload(m, &grpc.GenericServerStream[UnloadBytesRequest, UnloadBytesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ByterService_UnloadServer = grpc.ServerStreamingServer[UnloadBytesResponse]

// ByterService_ServiceDesc is the grpc.ServiceDesc for ByterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ByterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GophKeeper.server.proto.ByterService",
	HandlerType: (*ByterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _ByterService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Unload",
			Handler:       _ByterService_Unload_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/proto/byter_service.proto",
}
