// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: server/proto/byter_service.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBytesRequest) Reset() {
	*x = UploadBytesRequest{}
	mi := &file_server_proto_byter_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBytesRequest) ProtoMessage() {}

func (x *UploadBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_byter_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBytesRequest.ProtoReflect.Descriptor instead.
func (*UploadBytesRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_byter_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBytesRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadBytesRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadBytesRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBytesResponse) Reset() {
	*x = UploadBytesResponse{}
	mi := &file_server_proto_byter_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBytesResponse) ProtoMessage() {}

func (x *UploadBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_byter_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBytesResponse.ProtoReflect.Descriptor instead.
func (*UploadBytesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_byter_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBytesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadBytesResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UploadBytesResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type UnloadBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadBytesRequest) Reset() {
	*x = UnloadBytesRequest{}
	mi := &file_server_proto_byter_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadBytesRequest) ProtoMessage() {}

func (x *UnloadBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_byter_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadBytesRequest.ProtoReflect.Descriptor instead.
func (*UnloadBytesRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_byter_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnloadBytesRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UnloadBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadBytesResponse) Reset() {
	*x = UnloadBytesResponse{}
	mi := &file_server_proto_byter_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadBytesResponse) ProtoMessage() {}

func (x *UnloadBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_byter_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadBytesResponse.ProtoReflect.Descriptor instead.
func (*UnloadBytesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_byter_service_proto_rawDescGZIP(), []int{3}
}

func (x *UnloadBytesResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UnloadBytesResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UnloadBytesResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UnloadBytesResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_server_proto_byter_service_proto protoreflect.FileDescriptor

const file_server_proto_byter_service_proto_rawDesc = "" +
	"\n" +
	" server/proto/byter_service.proto\x12\x17GophKeeper.server.proto\"i\n" +
	"\x12UploadBytesRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"j\n" +
	"\x13UploadBytesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\tupdatedAt\x18\x02 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\"0\n" +
	"\x12UnloadBytesRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\x88\x01\n" +
	"\x13UnloadBytesResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt2\xdc\x01\n" +
	"\fByterService\x12e\n" +
	"\x06Upload\x12+.GophKeeper.server.proto.UploadBytesRequest\x1a,.GophKeeper.server.proto.UploadBytesResponse(\x01\x12e\n" +
	"\x06Unload\x12+.GophKeeper.server.proto.UnloadBytesRequest\x1a,.GophKeeper.server.proto.UnloadBytesResponse0\x01B5Z3github.com/boginskiy/GophKeeper/server/internal/rpcb\x06proto3"

var (
	file_server_proto_byter_service_proto_rawDescOnce sync.Once
	file_server_proto_byter_service_proto_rawDescData []byte
)

func file_server_proto_byter_service_proto_rawDescGZIP() []byte {
	file_server_proto_byter_service_proto_rawDescOnce.Do(func() {
		file_server_proto_byter_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_byter_service_proto_rawDesc), len(file_server_proto_byter_service_proto_rawDesc)))
	})
	return file_server_proto_byter_service_proto_rawDescData
}

var file_server_proto_byter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_proto_byter_service_proto_goTypes = []any{
	(*UploadBytesRequest)(nil),  // 0: GophKeeper.server.proto.UploadBytesRequest
	(*UploadBytesResponse)(nil), // 1: GophKeeper.server.proto.UploadBytesResponse
	(*UnloadBytesRequest)(nil),  // 2: GophKeeper.server.proto.UnloadBytesRequest
	(*UnloadBytesResponse)(nil), // 3: GophKeeper.server.proto.UnloadBytesResponse
}
var file_server_proto_byter_service_proto_depIdxs = []int32{
	0, // 0: GophKeeper.server.proto.ByterService.Upload:input_type -> GophKeeper.server.proto.UploadBytesRequest
	2, // 1: GophKeeper.server.proto.ByterService.Unload:input_type -> GophKeeper.server.proto.UnloadBytesRequest
	1, // 2: GophKeeper.server.proto.ByterService.Upload:output_type -> GophKeeper.server.proto.UploadBytesResponse
	3, // 3: GophKeeper.server.proto.ByterService.Unload:output_type -> GophKeeper.server.proto.UnloadBytesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_byter_service_proto_init() }
func file_server_proto_byter_service_proto_init() {
	if File_server_proto_byter_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_byter_service_proto_rawDesc), len(file_server_proto_byter_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_byter_service_proto_goTypes,
		DependencyIndexes: file_server_proto_byter_service_proto_depIdxs,
		MessageInfos:      file_server_proto_byter_service_proto_msgTypes,
	}.Build()
	File_server_proto_byter_service_proto = out.File
	file_server_proto_byter_service_proto_goTypes = nil
	file_server_proto_byter_service_proto_depIdxs = nil
}
