// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: server/proto/texter_service.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_server_proto_texter_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{0}
}

func (x *TextResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ListActivate  []int64                `protobuf:"varint,5,rep,packed,name=listActivate,proto3" json:"listActivate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_server_proto_texter_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateRequest) GetListActivate() []int64 {
	if x != nil {
		return x.ListActivate
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_server_proto_texter_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_server_proto_texter_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_server_proto_texter_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReadResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReadAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllRequest) Reset() {
	*x = ReadAllRequest{}
	mi := &file_server_proto_texter_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllRequest) ProtoMessage() {}

func (x *ReadAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllRequest.ProtoReflect.Descriptor instead.
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReadAllRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type ReadAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TextResponses []*TextResponse        `protobuf:"bytes,2,rep,name=textResponses,proto3" json:"textResponses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllResponse) Reset() {
	*x = ReadAllResponse{}
	mi := &file_server_proto_texter_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllResponse) ProtoMessage() {}

func (x *ReadAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllResponse.ProtoReflect.Descriptor instead.
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadAllResponse) GetTextResponses() []*TextResponse {
	if x != nil {
		return x.TextResponses
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_server_proto_texter_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_server_proto_texter_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_texter_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_texter_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_server_proto_texter_service_proto protoreflect.FileDescriptor

const file_server_proto_texter_service_proto_rawDesc = "" +
	"\n" +
	"!server/proto/texter_service.proto\x12\x17GophKeeper.server.proto\"T\n" +
	"\fTextResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\tR\tupdatedAt\"\x85\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\"\n" +
	"\flistActivate\x18\x05 \x03(\x03R\flistActivate\"F\n" +
	"\x0eCreateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\tupdatedAt\x18\x02 \x01(\tR\tupdatedAt\"7\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\"l\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\":\n" +
	"\x0eReadAllRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\"v\n" +
	"\x0fReadAllResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12K\n" +
	"\rtextResponses\x18\x02 \x03(\v2%.GophKeeper.server.proto.TextResponseR\rtextResponses\"9\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\"<\n" +
	"\x0eDeleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xd3\x03\n" +
	"\rTexterService\x12Y\n" +
	"\x06Create\x12&.GophKeeper.server.proto.CreateRequest\x1a'.GophKeeper.server.proto.CreateResponse\x12S\n" +
	"\x04Read\x12$.GophKeeper.server.proto.ReadRequest\x1a%.GophKeeper.server.proto.ReadResponse\x12\\\n" +
	"\aReadAll\x12'.GophKeeper.server.proto.ReadAllRequest\x1a(.GophKeeper.server.proto.ReadAllResponse\x12Y\n" +
	"\x06Update\x12&.GophKeeper.server.proto.CreateRequest\x1a'.GophKeeper.server.proto.CreateResponse\x12Y\n" +
	"\x06Delete\x12&.GophKeeper.server.proto.DeleteRequest\x1a'.GophKeeper.server.proto.DeleteResponseB5Z3github.com/boginskiy/GophKeeper/server/internal/rpcb\x06proto3"

var (
	file_server_proto_texter_service_proto_rawDescOnce sync.Once
	file_server_proto_texter_service_proto_rawDescData []byte
)

func file_server_proto_texter_service_proto_rawDescGZIP() []byte {
	file_server_proto_texter_service_proto_rawDescOnce.Do(func() {
		file_server_proto_texter_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_texter_service_proto_rawDesc), len(file_server_proto_texter_service_proto_rawDesc)))
	})
	return file_server_proto_texter_service_proto_rawDescData
}

var file_server_proto_texter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_proto_texter_service_proto_goTypes = []any{
	(*TextResponse)(nil),    // 0: GophKeeper.server.proto.TextResponse
	(*CreateRequest)(nil),   // 1: GophKeeper.server.proto.CreateRequest
	(*CreateResponse)(nil),  // 2: GophKeeper.server.proto.CreateResponse
	(*ReadRequest)(nil),     // 3: GophKeeper.server.proto.ReadRequest
	(*ReadResponse)(nil),    // 4: GophKeeper.server.proto.ReadResponse
	(*ReadAllRequest)(nil),  // 5: GophKeeper.server.proto.ReadAllRequest
	(*ReadAllResponse)(nil), // 6: GophKeeper.server.proto.ReadAllResponse
	(*DeleteRequest)(nil),   // 7: GophKeeper.server.proto.DeleteRequest
	(*DeleteResponse)(nil),  // 8: GophKeeper.server.proto.DeleteResponse
}
var file_server_proto_texter_service_proto_depIdxs = []int32{
	0, // 0: GophKeeper.server.proto.ReadAllResponse.textResponses:type_name -> GophKeeper.server.proto.TextResponse
	1, // 1: GophKeeper.server.proto.TexterService.Create:input_type -> GophKeeper.server.proto.CreateRequest
	3, // 2: GophKeeper.server.proto.TexterService.Read:input_type -> GophKeeper.server.proto.ReadRequest
	5, // 3: GophKeeper.server.proto.TexterService.ReadAll:input_type -> GophKeeper.server.proto.ReadAllRequest
	1, // 4: GophKeeper.server.proto.TexterService.Update:input_type -> GophKeeper.server.proto.CreateRequest
	7, // 5: GophKeeper.server.proto.TexterService.Delete:input_type -> GophKeeper.server.proto.DeleteRequest
	2, // 6: GophKeeper.server.proto.TexterService.Create:output_type -> GophKeeper.server.proto.CreateResponse
	4, // 7: GophKeeper.server.proto.TexterService.Read:output_type -> GophKeeper.server.proto.ReadResponse
	6, // 8: GophKeeper.server.proto.TexterService.ReadAll:output_type -> GophKeeper.server.proto.ReadAllResponse
	2, // 9: GophKeeper.server.proto.TexterService.Update:output_type -> GophKeeper.server.proto.CreateResponse
	8, // 10: GophKeeper.server.proto.TexterService.Delete:output_type -> GophKeeper.server.proto.DeleteResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_proto_texter_service_proto_init() }
func file_server_proto_texter_service_proto_init() {
	if File_server_proto_texter_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_texter_service_proto_rawDesc), len(file_server_proto_texter_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_texter_service_proto_goTypes,
		DependencyIndexes: file_server_proto_texter_service_proto_depIdxs,
		MessageInfos:      file_server_proto_texter_service_proto_msgTypes,
	}.Build()
	File_server_proto_texter_service_proto = out.File
	file_server_proto_texter_service_proto_goTypes = nil
	file_server_proto_texter_service_proto_depIdxs = nil
}
