// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: server/proto/auth_service.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistRequest) Reset() {
	*x = RegistRequest{}
	mi := &file_server_proto_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistRequest) ProtoMessage() {}

func (x *RegistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistRequest.ProtoReflect.Descriptor instead.
func (*RegistRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegistRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistRequest) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

type RegistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistResponse) Reset() {
	*x = RegistResponse{}
	mi := &file_server_proto_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistResponse) ProtoMessage() {}

func (x *RegistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistResponse.ProtoReflect.Descriptor instead.
func (*RegistResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegistResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecovRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecovRequest) Reset() {
	*x = RecovRequest{}
	mi := &file_server_proto_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecovRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecovRequest) ProtoMessage() {}

func (x *RecovRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecovRequest.ProtoReflect.Descriptor instead.
func (*RecovRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *RecovRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RecovRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RecovResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecovResponse) Reset() {
	*x = RecovResponse{}
	mi := &file_server_proto_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecovResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecovResponse) ProtoMessage() {}

func (x *RecovResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecovResponse.ProtoReflect.Descriptor instead.
func (*RecovResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *RecovResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_server_proto_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_server_proto_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_server_proto_auth_service_proto protoreflect.FileDescriptor

const file_server_proto_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1fserver/proto/auth_service.proto\x12\x17GophKeeper.server.proto\"\x7f\n" +
	"\rRegistRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12 \n" +
	"\vphonenumber\x18\x04 \x01(\tR\vphonenumber\"(\n" +
	"\x0eRegistResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"@\n" +
	"\fRecovRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"'\n" +
	"\rRecovResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"?\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"&\n" +
	"\fAuthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa8\x02\n" +
	"\vAuthService\x12_\n" +
	"\fRegistration\x12&.GophKeeper.server.proto.RegistRequest\x1a'.GophKeeper.server.proto.RegistResponse\x12]\n" +
	"\x0eAuthentication\x12$.GophKeeper.server.proto.AuthRequest\x1a%.GophKeeper.server.proto.AuthResponse\x12Y\n" +
	"\bRecovery\x12%.GophKeeper.server.proto.RecovRequest\x1a&.GophKeeper.server.proto.RecovResponseB5Z3github.com/boginskiy/GophKeeper/server/internal/rpcb\x06proto3"

var (
	file_server_proto_auth_service_proto_rawDescOnce sync.Once
	file_server_proto_auth_service_proto_rawDescData []byte
)

func file_server_proto_auth_service_proto_rawDescGZIP() []byte {
	file_server_proto_auth_service_proto_rawDescOnce.Do(func() {
		file_server_proto_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_auth_service_proto_rawDesc), len(file_server_proto_auth_service_proto_rawDesc)))
	})
	return file_server_proto_auth_service_proto_rawDescData
}

var file_server_proto_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_proto_auth_service_proto_goTypes = []any{
	(*RegistRequest)(nil),  // 0: GophKeeper.server.proto.RegistRequest
	(*RegistResponse)(nil), // 1: GophKeeper.server.proto.RegistResponse
	(*RecovRequest)(nil),   // 2: GophKeeper.server.proto.RecovRequest
	(*RecovResponse)(nil),  // 3: GophKeeper.server.proto.RecovResponse
	(*AuthRequest)(nil),    // 4: GophKeeper.server.proto.AuthRequest
	(*AuthResponse)(nil),   // 5: GophKeeper.server.proto.AuthResponse
}
var file_server_proto_auth_service_proto_depIdxs = []int32{
	0, // 0: GophKeeper.server.proto.AuthService.Registration:input_type -> GophKeeper.server.proto.RegistRequest
	4, // 1: GophKeeper.server.proto.AuthService.Authentication:input_type -> GophKeeper.server.proto.AuthRequest
	2, // 2: GophKeeper.server.proto.AuthService.Recovery:input_type -> GophKeeper.server.proto.RecovRequest
	1, // 3: GophKeeper.server.proto.AuthService.Registration:output_type -> GophKeeper.server.proto.RegistResponse
	5, // 4: GophKeeper.server.proto.AuthService.Authentication:output_type -> GophKeeper.server.proto.AuthResponse
	3, // 5: GophKeeper.server.proto.AuthService.Recovery:output_type -> GophKeeper.server.proto.RecovResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_auth_service_proto_init() }
func file_server_proto_auth_service_proto_init() {
	if File_server_proto_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_auth_service_proto_rawDesc), len(file_server_proto_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_auth_service_proto_goTypes,
		DependencyIndexes: file_server_proto_auth_service_proto_depIdxs,
		MessageInfos:      file_server_proto_auth_service_proto_msgTypes,
	}.Build()
	File_server_proto_auth_service_proto = out.File
	file_server_proto_auth_service_proto_goTypes = nil
	file_server_proto_auth_service_proto_depIdxs = nil
}
