// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: server/proto/keeper_service.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistUserRequest) Reset() {
	*x = RegistUserRequest{}
	mi := &file_server_proto_keeper_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistUserRequest) ProtoMessage() {}

func (x *RegistUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_keeper_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistUserRequest.ProtoReflect.Descriptor instead.
func (*RegistUserRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_keeper_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegistUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistUserRequest) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

type RegistUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistUserResponse) Reset() {
	*x = RegistUserResponse{}
	mi := &file_server_proto_keeper_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistUserResponse) ProtoMessage() {}

func (x *RegistUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_keeper_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistUserResponse.ProtoReflect.Descriptor instead.
func (*RegistUserResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_keeper_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegistUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	mi := &file_server_proto_keeper_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_keeper_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_keeper_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_server_proto_keeper_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_keeper_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_keeper_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuthUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_server_proto_keeper_service_proto protoreflect.FileDescriptor

const file_server_proto_keeper_service_proto_rawDesc = "" +
	"\n" +
	"!server/proto/keeper_service.proto\x12\x17GophKeeper.server.proto\"\x83\x01\n" +
	"\x11RegistUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12 \n" +
	"\vphonenumber\x18\x04 \x01(\tR\vphonenumber\",\n" +
	"\x12RegistUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"C\n" +
	"\x0fAuthUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x10AuthUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xd7\x01\n" +
	"\rKeeperService\x12e\n" +
	"\n" +
	"RegistUser\x12*.GophKeeper.server.proto.RegistUserRequest\x1a+.GophKeeper.server.proto.RegistUserResponse\x12_\n" +
	"\bAuthUser\x12(.GophKeeper.server.proto.AuthUserRequest\x1a).GophKeeper.server.proto.AuthUserResponseB6Z4github.com/boginskiy/GophKeeper/server/internal/grpcb\x06proto3"

var (
	file_server_proto_keeper_service_proto_rawDescOnce sync.Once
	file_server_proto_keeper_service_proto_rawDescData []byte
)

func file_server_proto_keeper_service_proto_rawDescGZIP() []byte {
	file_server_proto_keeper_service_proto_rawDescOnce.Do(func() {
		file_server_proto_keeper_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_keeper_service_proto_rawDesc), len(file_server_proto_keeper_service_proto_rawDesc)))
	})
	return file_server_proto_keeper_service_proto_rawDescData
}

var file_server_proto_keeper_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_proto_keeper_service_proto_goTypes = []any{
	(*RegistUserRequest)(nil),  // 0: GophKeeper.server.proto.RegistUserRequest
	(*RegistUserResponse)(nil), // 1: GophKeeper.server.proto.RegistUserResponse
	(*AuthUserRequest)(nil),    // 2: GophKeeper.server.proto.AuthUserRequest
	(*AuthUserResponse)(nil),   // 3: GophKeeper.server.proto.AuthUserResponse
}
var file_server_proto_keeper_service_proto_depIdxs = []int32{
	0, // 0: GophKeeper.server.proto.KeeperService.RegistUser:input_type -> GophKeeper.server.proto.RegistUserRequest
	2, // 1: GophKeeper.server.proto.KeeperService.AuthUser:input_type -> GophKeeper.server.proto.AuthUserRequest
	1, // 2: GophKeeper.server.proto.KeeperService.RegistUser:output_type -> GophKeeper.server.proto.RegistUserResponse
	3, // 3: GophKeeper.server.proto.KeeperService.AuthUser:output_type -> GophKeeper.server.proto.AuthUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_keeper_service_proto_init() }
func file_server_proto_keeper_service_proto_init() {
	if File_server_proto_keeper_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_keeper_service_proto_rawDesc), len(file_server_proto_keeper_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_keeper_service_proto_goTypes,
		DependencyIndexes: file_server_proto_keeper_service_proto_depIdxs,
		MessageInfos:      file_server_proto_keeper_service_proto_msgTypes,
	}.Build()
	File_server_proto_keeper_service_proto = out.File
	file_server_proto_keeper_service_proto_goTypes = nil
	file_server_proto_keeper_service_proto_depIdxs = nil
}
